server:
  address: ":8081"
  server_name: maltose
  server_root: ./public
  server_locale: zh
  read_timeout: 30s
  openapi_path: /api.json
  swagger_path: /swagger
  logger:
    level: debug
    format: text

logger:
  level: debug
  path: ./logs/dev.log
  format: json
  time_format: "2006-01-02 15:04:05"

database:
  type: mysql
  db_name: test
  logger:
    level: debug
    path: ./logs/dev.log

mse:
  mseDataId: "d_fino_consume_w"
  mseGroup: "db"
